import type { WeaponDefinition, WeaponId, WeaponState } from './types';

export const WEAPONS: Record<WeaponId, WeaponDefinition> = {
  'pulse-rifle': {
    id: 'pulse-rifle',
    label: 'Rifle de pulso',
    role: 'Automático equilibrado',
    automatic: true,
    fireInterval: 0.105,
    damage: 13,
    headMultiplier: 1.35,
    headshotMode: 'bonus',
    magazineSize: 32,
    startingReserve: 128,
    maxReserve: 224,
    reloadSeconds: 1.75,
    range: 58,
    spread: 0.00175,
    maxSpread: 0.05236,
    bloomPerShot: 0.38,
    bloomRecovery: 2,
    pellets: 1,
    magnetismAngle: 0.0096,
    magnetismRange: 32,
    recoil: 0.012,
    tint: 0x47d7c7,
  },
  sidearm: {
    id: 'sidearm',
    label: 'Pistola Vector',
    role: 'Precisión semiautomática',
    automatic: false,
    fireInterval: 0.286,
    damage: 24,
    headMultiplier: 2,
    headshotMode: 'precision',
    magazineSize: 12,
    startingReserve: 48,
    maxReserve: 84,
    reloadSeconds: 1.9,
    range: 72,
    spread: 0.00175,
    maxSpread: 0.018,
    bloomPerShot: 0.72,
    bloomRecovery: 1.8,
    pellets: 1,
    zoomFov: [63],
    magnetismAngle: 0.0062,
    magnetismRange: 42,
    recoil: 0.025,
    tint: 0xa7b7d2,
  },
  'battle-rifle': {
    id: 'battle-rifle',
    label: 'Rifle de batalla',
    role: 'Ráfaga de media distancia',
    automatic: false,
    fireInterval: 0.4,
    damage: 9,
    headMultiplier: 2,
    headshotMode: 'precision',
    magazineSize: 36,
    startingReserve: 108,
    maxReserve: 180,
    reloadSeconds: 1.85,
    range: 86,
    spread: 0.00262,
    maxSpread: 0.00873,
    bloomPerShot: 0.2,
    bloomRecovery: 1.65,
    pellets: 1,
    burstCount: 3,
    burstInterval: 1 / 15,
    burstSpread: [0.00262, 0.00463, 0.00663],
    ballisticSpeed: 180,
    zoomFov: [53],
    magnetismAngle: 0.0052,
    magnetismRange: 52,
    recoil: 0.018,
    tint: 0x6fa9ce,
  },
  sniper: {
    id: 'sniper',
    label: 'Rifle de precisión',
    role: 'Potencia a larga distancia',
    automatic: false,
    fireInterval: 0.85,
    damage: 115,
    headMultiplier: 2.25,
    headshotMode: 'precision',
    magazineSize: 4,
    startingReserve: 12,
    maxReserve: 20,
    reloadSeconds: 2.4,
    range: 180,
    spread: 0.00035,
    maxSpread: 0.00035,
    bloomPerShot: 0,
    bloomRecovery: 2,
    pellets: 1,
    zoomFov: [17.15, 8.62],
    magnetismAngle: 0.0026,
    magnetismRange: 72,
    recoil: 0.065,
    tint: 0x9e84e8,
  },
  shotgun: {
    id: 'shotgun',
    label: 'Escopeta de brecha',
    role: 'Devastadora a corta distancia',
    automatic: false,
    fireInterval: 0.95,
    damage: 19,
    headMultiplier: 1.15,
    headshotMode: 'bonus',
    magazineSize: 6,
    startingReserve: 24,
    maxReserve: 42,
    reloadSeconds: 0.72,
    range: 16,
    spread: 0.105,
    maxSpread: 0.105,
    bloomPerShot: 0,
    bloomRecovery: 2,
    pellets: 12,
    reloadStyle: 'shell',
    magnetismAngle: 0.0175,
    magnetismRange: 11,
    damageFalloffStart: 4,
    damageFalloffEnd: 16,
    minimumDamageScale: 0.32,
    recoil: 0.075,
    tint: 0xff9b71,
  },
  'rocket-launcher': {
    id: 'rocket-launcher',
    label: 'Lanzacohetes Nova',
    role: 'Daño explosivo de área',
    automatic: false,
    fireInterval: 1.35,
    damage: 220,
    headMultiplier: 1,
    headshotMode: 'none',
    magazineSize: 2,
    startingReserve: 4,
    maxReserve: 8,
    reloadSeconds: 4.15,
    range: 110,
    spread: 0,
    maxSpread: 0,
    bloomPerShot: 0,
    bloomRecovery: 2,
    pellets: 1,
    zoomFov: [60],
    recoil: 0.09,
    projectile: 'rocket',
    splashRadius: 5.5,
    tint: 0xe75e65,
  },
};

export const createWeaponState = (id: WeaponId): WeaponState => {
  const definition = WEAPONS[id];
  return {
    id,
    magazine: definition.magazineSize,
    reserve: definition.startingReserve,
    cooldown: 0,
    reloadTimer: 0,
    bloom: 0,
    burstRemaining: 0,
    burstRoundIndex: 0,
    burstTimer: 0,
  };
};

export const DEFAULT_LOADOUT: readonly WeaponId[] = ['pulse-rifle', 'sidearm'];
export const TOWER_LOADOUT: readonly WeaponId[] = ['shotgun', 'sidearm'];
