import type { WeaponDefinition, WeaponId, WeaponState } from './types';

export const WEAPONS: Record<WeaponId, WeaponDefinition> = {
  'pulse-rifle': {
    id: 'pulse-rifle',
    label: 'Rifle de pulso',
    role: 'Automático equilibrado',
    automatic: true,
    fireInterval: 0.105,
    damage: 13,
    headMultiplier: 1.6,
    magazineSize: 32,
    startingReserve: 128,
    maxReserve: 224,
    reloadSeconds: 1.75,
    range: 58,
    spread: 0.018,
    pellets: 1,
    recoil: 0.012,
    tint: 0x47d7c7,
  },
  sidearm: {
    id: 'sidearm',
    label: 'Pistola Vector',
    role: 'Precisión semiautomática',
    automatic: false,
    fireInterval: 0.286,
    damage: 32,
    headMultiplier: 1.6,
    magazineSize: 12,
    startingReserve: 48,
    maxReserve: 84,
    reloadSeconds: 1.35,
    range: 72,
    spread: 0.006,
    pellets: 1,
    recoil: 0.025,
    tint: 0xa7b7d2,
  },
  'battle-rifle': {
    id: 'battle-rifle',
    label: 'Rifle de batalla',
    role: 'Ráfaga de media distancia',
    automatic: false,
    fireInterval: 0.34,
    damage: 14,
    headMultiplier: 1.55,
    magazineSize: 36,
    startingReserve: 108,
    maxReserve: 180,
    reloadSeconds: 1.85,
    range: 86,
    spread: 0.005,
    pellets: 3,
    recoil: 0.018,
    tint: 0x6fa9ce,
  },
  sniper: {
    id: 'sniper',
    label: 'Rifle de precisión',
    role: 'Potencia a larga distancia',
    automatic: false,
    fireInterval: 1.15,
    damage: 90,
    headMultiplier: 2.25,
    magazineSize: 4,
    startingReserve: 12,
    maxReserve: 20,
    reloadSeconds: 2.4,
    range: 180,
    spread: 0.0006,
    pellets: 1,
    recoil: 0.065,
    tint: 0x9e84e8,
  },
  shotgun: {
    id: 'shotgun',
    label: 'Escopeta de brecha',
    role: 'Devastadora a corta distancia',
    automatic: false,
    fireInterval: 0.95,
    damage: 16,
    headMultiplier: 1.1,
    magazineSize: 6,
    startingReserve: 24,
    maxReserve: 42,
    reloadSeconds: 2.15,
    range: 16,
    spread: 0.072,
    pellets: 12,
    recoil: 0.075,
    tint: 0xff9b71,
  },
  'rocket-launcher': {
    id: 'rocket-launcher',
    label: 'Lanzacohetes Nova',
    role: 'Daño explosivo de área',
    automatic: false,
    fireInterval: 1.35,
    damage: 220,
    headMultiplier: 1,
    magazineSize: 2,
    startingReserve: 4,
    maxReserve: 8,
    reloadSeconds: 2.8,
    range: 110,
    spread: 0,
    pellets: 1,
    recoil: 0.09,
    projectile: 'rocket',
    splashRadius: 5.5,
    tint: 0xe75e65,
  },
};

export const createWeaponState = (id: WeaponId): WeaponState => {
  const definition = WEAPONS[id];
  return {
    id,
    magazine: definition.magazineSize,
    reserve: definition.startingReserve,
    cooldown: 0,
    reloadTimer: 0,
  };
};

export const DEFAULT_LOADOUT: readonly WeaponId[] = ['pulse-rifle', 'sidearm'];
export const TOWER_LOADOUT: readonly WeaponId[] = ['shotgun', 'sidearm'];

export const weaponLabel = (id: WeaponId): string => WEAPONS[id].label;
